import type { Metadata } from "next";
import { Domine } from "next/font/google"; // <-- add this
import "./globals.css";

const domine = Domine({
  subsets: ["latin"],
  variable: "--font-domine", // CSS variable for Tailwind/Global use
  weight: ["400", "700"],    // optional: choose weights you want
});

export const metadata: Metadata = {
  title: "Ilani's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${domine.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
