import type { Metadata } from "next";
import { Cormorant_Garamond, Manrope } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/next"

// Manrope: navbar + main body text
const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
});

// Cormorant Garamond: name, large quotes, and standout display text
const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  variable: "--font-cormorantgaramound",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Ilani's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} ${cormorant.variable} antialiased`}>
        {children}
        <Analytics />
      </body>
    </html>
  );
}
